---
title: "Analyzing HOBO Temperature Data"
author: "Connor Flynn"
date: "10/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse,
                here,
                janitor,
                lubridate,
                plotly,
                RColorBrewer)



```



Read in HOBO temperature data

```{r}
Kalauhaihai_Makaha <- read_csv(here("data/June_October_2022_Fishponds/BB_20970109.csv"))

KanewaiFishpondLedgeEdgeNorfolk <- read_csv(here("data/June_October_2022_Fishponds/GG_20970122.csv"))
  
KanewaiSpringLedge <- read_csv(here("data/June_October_2022_Fishponds/O_20970093.csv"))
  
KanewaiFishpondShade <- read_csv(here("data/June_October_2022_Fishponds/OYG_20970123.csv"))
  
KanewaiAuwaiMakaiSideFootBridge <- read_csv(here("data/June_October_2022_Fishponds/YG_20970107.csv"))
  
```





Clean Column Names

```{r}
Kalauhaihai_Makaha <- Kalauhaihai_Makaha %>% 
  clean_names

KanewaiFishpondLedgeEdgeNorfolk <- KanewaiFishpondLedgeEdgeNorfolk %>% 
  clean_names

KanewaiSpringLedge <- KanewaiSpringLedge %>% 
  clean_names

KanewaiFishpondShade <- KanewaiFishpondShade %>% 
  clean_names

KanewaiAuwaiMakaiSideFootBridge <- KanewaiAuwaiMakaiSideFootBridge %>% 
  clean_names


```


Merge Date and Time Columns

```{r}
Kalauhaihai_Makaha$date_time = dmy_hms(paste(Kalauhaihai_Makaha$date, Kalauhaihai_Makaha$time))

KanewaiFishpondLedgeEdgeNorfolk$date_time = dmy_hms(paste(KanewaiFishpondLedgeEdgeNorfolk$date, KanewaiFishpondLedgeEdgeNorfolk$time))

KanewaiSpringLedge$date_time = dmy_hms(paste(KanewaiSpringLedge$date, KanewaiSpringLedge$time))

KanewaiFishpondShade$date_time = dmy_hms(paste(KanewaiFishpondShade$date, KanewaiFishpondShade$time))

KanewaiAuwaiMakaiSideFootBridge$date_time = dmy_hms(paste(KanewaiAuwaiMakaiSideFootBridge$date, KanewaiAuwaiMakaiSideFootBridge$time))


```


Add Location Column

```{r}
Kalauhaihai_Makaha$location = "Kalauhaihai_Makaha"

KanewaiFishpondLedgeEdgeNorfolk$location = "KanewaiFishpondLedgeEdgeNorfolk"

KanewaiSpringLedge$location = "KanewaiSpringLedge"

KanewaiFishpondShade$location = "KanewaiFishpondShade"

KanewaiAuwaiMakaiSideFootBridge$location = "KanewaiAuwaiMakaiSideFootBridge"

```


Create a List of Dataframes to Join

```{r}
df_list <- list(Kalauhaihai_Makaha, KanewaiFishpondLedgeEdgeNorfolk, KanewaiSpringLedge, KanewaiFishpondShade, KanewaiAuwaiMakaiSideFootBridge)
```



Combine Dataframes in List

```{r}
all_data <- Reduce(function(x, y) merge(x, y, all=TRUE), df_list, accumulate=FALSE)
```



Plot Data

```{r}
ggplot(data = all_data, aes(x = date_time, y = temp_c_c_1, colour = location))+
  geom_line() +
  theme_minimal()



```



Trim ends 


```{r}
all_data_trimmed <- all_data[all_data$date_time > "2022-06-11" &    # Extract data frame subset
                   all_data$date_time < "2022-10-5", ]
```


```{r}
ggplot(data = all_data_trimmed, aes(x = date_time, y = temp_c_c_1, colour = location))+
  geom_line() +
  theme_minimal()
```

```{r}
ggplot(data = all_data_trimmed, aes(x = date_time, y = temp_c_c_1, colour = location))+
  geom_line() +
  theme_minimal() + 
  facet_wrap(~location)
```

```{r}
plot <- ggplot(data = all_data_trimmed, aes(x = date_time, y = temp_c_c_1, colour = location))+
  geom_line() +
  theme_minimal() + 
  facet_wrap(~location) +
  geom_smooth(method = "lm")

plot
```

```{r}
ggplotly(plot)
```



Range

```{r}
all_data_trimmed_sep_date_time <- all_data_trimmed %>%
  tidyr::separate('date_time',
                  into = c('date_new', 'time_new'),
                  sep= ' ',
                  remove = FALSE)
head(all_data_trimmed_sep_date_time)
```


```{r}
all_data_trimmed_sep_date <- all_data_trimmed_sep_date_time %>%
  tidyr::separate('date_new',
                  into = c('year', 'month', 'day'),
                  sep= '-',
                  remove = FALSE)
head(all_data_trimmed_sep_date)
```

```{r}
all_data_range <- all_data_trimmed_sep_date %>%
  group_by(year, month, day, location, date_new)%>%
  summarise(min_temp = min(temp_c_c_1), max_temp = max(temp_c_c_1))%>%
  mutate(range = max_temp-min_temp)

head(all_data_range, digits=20)
```

```{r}
ggplot(data=all_data_range, 
                   aes(x=as.Date(date_new, format = "%Y - %m - %d"), 
                       y=range, colour=location)) +
   


  geom_smooth()+
  theme_minimal()+
  theme(axis.text.x = element_text(margin = margin(t=5)))+
  labs(title="Daily temperature range", y="Mean daily temperature range (°C) with 95% CI ", x="Date")+
  scale_color_brewer(palette="Set3") 
```


